using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Domain.Models;

namespace Infrastructure.Data.Context
{
    public class DatabaseSeed
    {
        public static void Seed(ModelBuilder Builder)
        {
            foreach (var entityType in Builder.Model.GetEntityTypes().Where(t => t.ClrType.IsSubclassOf(typeof(BaseEntity))))
            {
                Builder.Entity(entityType.Name,
                    X =>
                    {
                        X.Property("AddedDate").HasDefaultValueSql("GETDATE()");
                        X.Property("IsDeleted").HasDefaultValue(false);
                    });
            }
            /************************************************************************************************/
            List<Role> RolesList = new List<Role>()
            {
                new Role()
                {
                    ID = 1,
                    Name = "مدیر سیستم",
                    NormalizedName = "مدیر سیستم",
                    ConcurrencyStamp = Guid.NewGuid().ToString("D"),
                },
                new Role()
                {
                    ID = 2,
                    Name = "فروشنده",
                    NormalizedName = "فروشنده",
                    ConcurrencyStamp = Guid.NewGuid().ToString("D"),
                },
                new Role()
                {
                    ID = 3,
                    Name = "خریدار",
                    NormalizedName = "خریدار",
                    ConcurrencyStamp = Guid.NewGuid().ToString("D"),
                },
                new Role()
                {
                    ID = 4,
                    Name = "بازاریاب",
                    NormalizedName = "بازاریاب",
                    ConcurrencyStamp = Guid.NewGuid().ToString("D"),
                },
            };
            Builder.Entity<Role>().HasData(RolesList);
            /************************************************************************************************/
            List<User> UsersList = new List<User>()
            {
                new User()
                 {
                     ID = 1,
                     Gender = 1,
                     Name = "مهرداد",
                     Family = "مهبد",
                     CityId =6,
                     UserName = "09368977702",
                     Password="123",
                     NormalizedUserName = "Mehrdad2017",
                     Email = "Mehrdad2017@yahoo.com",
                     LockoutEnabled = true,
                     PhoneNumber = "09368977702",
                     PhoneNumberConfirmed =true,
                     SecurityStamp = Guid.NewGuid().ToString("D"),
                 },
            };
            /*Only User*************************************************************************************/
            /*User User2 = new User()
            {
                Id = 1,
                Gender = 1,
                Name = "مهرداد",
                Family = "مهبد",
                UserName = "Mehrdad2017",
                NormalizedUserName = "Mehrdad2017",
                Email = "Mehrdad2017@yahoo.com",
                LockoutEnabled = true,
                PhoneNumber = "09368977702",
                SecurityStamp = Guid.NewGuid().ToString("D"),
            };
            PasswordHasher<User> PasswordHasher = new PasswordHasher<User>();
            User2.PasswordHash = PasswordHasher.HashPassword(User1, "123");
            Builder.Entity<User>().HasData(User);*/
            /***********************************************************************************************/
            /*
            PasswordHasher<User> PasswordHasher = new PasswordHasher<User>();
            foreach (User Item in UsersList)
            {
                Item.PasswordHash = PasswordHasher.HashPassword(Item, "123");
            }
            */
            //Builder.Entity<User>().HasData(UsersList);
            /************************************************************************************************/
            List<UserRole> UsersRolesList = new List<UserRole>()
            {
                new UserRole()
                {
                    ID=1,
                    UserId = 1,//مهرداد
                    RoleId = 1//مدیر سیستم 
                }
            };
            //Builder.Entity<UserRole>().HasData(UsersRolesList);
            /************************************************************************************************/
            List<Menu> MenusList = new List<Menu>()
            {
                new Menu()
                {
                    ID=1,
                    ParentId =  null,
                    Name="پروفایل",
                    Component =null,
                    Icon ="fa fa-chevron-circle-down",
                    IsSelective = true,
                },
                new Menu()
                {
                    ID=2,
                    ParentId =  1,
                    Name="ویرایش مشخصات",
                    Component ="Account",
                    Icon ="fas fa-user-edit",
                    IsSelective = true,
                },
                new Menu()
                {
                    ID=3,
                    ParentId =  1,
                    Name="تنظیمات",
                    Component =null,
                    Icon ="fas fa-cogs",
                    IsSelective = true,
                },
                new Menu()
                {
                    ID=4,
                    ParentId =  null,
                    Name="تعاریف",
                    Component =null,
                    Icon ="fa fa-chevron-circle-down",
                    IsSelective = true,
                },
                new Menu()
                {
                    ID=5,
                    ParentId = 4 ,
                    Name="نوع کالا",
                    //Controller = "TypeOfGoods",
                    //Action = "Index",
                    //Component ="PatientVisit",
                    Icon ="fas fa-text-height",
                    IsSelective = true,
                },
                new Menu()
                {
                    ID=6,
                    ParentId = 4 ,
                    Name="ویژگی",
                    Component ="RegistrationDoctorDrugs",
                    //Controller = "Feature",
                    //Action = "Index",
                    Icon ="fas fa-cogs",
                    IsSelective = true,
                }
            };
            Builder.Entity<Menu>().HasData(MenusList);
            /************************************************************************************************/
            List<RoleMenu> RoleMenusList = new List<RoleMenu>()
            {
              //Admin Role
              new RoleMenu()
              {
                  ID =1,
                  RoleId=1,
                  MenuId =1
              },
              new RoleMenu()
              {
                  ID =2,
                  RoleId=1,
                  MenuId =2
              },
              new RoleMenu()
              {
                  ID =3,
                  RoleId=1,
                  MenuId =3
              },
              new RoleMenu()
              {
                  ID =4,
                  RoleId=1,
                  MenuId =4
              },
              new RoleMenu()
              {
                  ID =5,
                  RoleId=1,
                  MenuId =5
              },
              //Programmer Role
              /***************/
            };
            Builder.Entity<RoleMenu>().HasData(RoleMenusList);
            /************************************************************************************************/
            List<UserMenu> UsersMenusList = new List<UserMenu>()
            {
              new UserMenu()
              {
                  ID=1,
                  UserId=1,
                  MenuId =6,
                  RegisteredUserId = 1
              },
            };
            //Builder.Entity<UserMenu>().HasData(UsersMenusList);
            /************************************************************************************************/
            List<Province> ProvincesList = new List<Province>()
            {
                new Province(){ID=1,Name="آذربایجان شرقی",PrePhoneNumber ="041"},
                new Province(){ID=2,Name="آذربایجان غربی",PrePhoneNumber ="044"},
                new Province(){ID=3,Name="اردبیل",PrePhoneNumber ="045"},
                new Province(){ID=4,Name="اصفهان",PrePhoneNumber ="031"},
                new Province(){ID=5,Name="البرز",PrePhoneNumber = "026"},
                new Province(){ID=6,Name="ایلام",PrePhoneNumber ="084"},
                new Province(){ID=7,Name="بوشهر",PrePhoneNumber ="077"},
                new Province(){ID=8,Name="تهران",PrePhoneNumber ="021"},
                new Province(){ID=9,Name="چهارمحال و بختیاری", PrePhoneNumber ="038"},
                new Province(){ID=10,Name="خراسان جنوبی",PrePhoneNumber ="066"},
                new Province(){ID=11,Name="خراسان رضوی", PrePhoneNumber ="051"},
                new Province(){ID=12,Name="خراسان شمالی",PrePhoneNumber ="058"},
                new Province(){ID=13,Name="خوزستان",PrePhoneNumber ="061"},
                new Province(){ID=14,Name="زنجان",PrePhoneNumber ="024"},
                new Province(){ID=15,Name="سمنان", PrePhoneNumber ="023"},
                new Province(){ID=16,Name="سیستان و بلوچستان",PrePhoneNumber ="054"},
                new Province(){ID=17,Name="فارس",PrePhoneNumber ="071"},
                new Province(){ID=18,Name="قزوین",PrePhoneNumber ="028"},
                new Province(){ID=19,Name="قم",PrePhoneNumber ="025"},
                new Province(){ID=20,Name="كردستان",PrePhoneNumber ="087"},
                new Province(){ID=21,Name="كرمان",PrePhoneNumber ="034"},
                new Province(){ID=22,Name="كرمانشاه", PrePhoneNumber ="083"},
                new Province(){ID=23,Name="كهگیلویه و بویراحمد",PrePhoneNumber ="047"},
                new Province(){ID=24,Name="گلستان",PrePhoneNumber ="017"},
                new Province(){ID=25,Name="گیلان",PrePhoneNumber ="013"},
                new Province(){ID=26,Name="لرستان",PrePhoneNumber ="066"},
                new Province(){ID=27,Name="مازندران",PrePhoneNumber ="011"},
                new Province(){ID=28,Name="مركزی",PrePhoneNumber ="086"},
                new Province(){ID=29,Name="هرمزگان",PrePhoneNumber ="076"},
                new Province(){ID=30,Name="همدان",PrePhoneNumber ="081"},
                new Province(){ID=31,Name = "یزد",PrePhoneNumber = "035"}
            };
            Builder.Entity<Province>().HasData(ProvincesList);
            /************************************************************************************************/
            List<City> CitiesList = new List<City>()
            {
               new City() {ID=1,  ProvinceId=1,Name = "آذرشهر"},
               new City(){ID=2,   ProvinceId=1,Name="اسكو"},
               new City(){ ID=3,  ProvinceId=1,Name= "اهر"},
               new City(){ ID=4,  ProvinceId=1,Name= "بستان آباد"},
               new City(){ ID=5,  ProvinceId=1,Name= "بناب",},
               new City(){ ID=6,  ProvinceId=1,Name= "تبریز"},
               new City(){ ID=7,  ProvinceId=1,Name="جلفا"},
               new City(){ ID=8,  ProvinceId=1,Name="چاراویماق"},
               new City(){ ID=9,  ProvinceId=1,Name="سراب"},
               new City(){ ID=10, ProvinceId=1,Name="شبستر"},
               new City(){ ID=11, ProvinceId=1,Name="عجبشیر"},
               new City(){ ID=12, ProvinceId=1,Name="كلیبر"},
               new City(){ ID=13, ProvinceId=1,Name="مراغه"},
               new City(){ ID=14, ProvinceId=1,Name="مرند"},
               new City(){ ID=15, ProvinceId=1,Name="ملكان"},
               new City(){ ID=16, ProvinceId=1,Name="میانه"},
               new City(){ ID=17, ProvinceId=1,Name="ورزقان"},
               new City(){ ID=18, ProvinceId=1,Name="هریس"},
               new City(){ ID=19, ProvinceId=1,Name="هشترود"},
               new City(){ ID=20, ProvinceId=2,Name="ارومیه"},
               new City(){ ID=21, ProvinceId=2,Name="اشنویه"},
               new City(){ ID=22, ProvinceId=2,Name="بوكان"},
               new City(){ ID=23, ProvinceId=2,Name="پیر انشهر"},
               new City(){ ID=24, ProvinceId=2,Name="تكاب"},
               new City(){ ID=25, ProvinceId=2,Name="چالدران"},
               new City(){ ID=26, ProvinceId=2,Name="خوی"},
               new City(){ ID=27, ProvinceId=2,Name="سردشت"},
               new City(){ ID=28, ProvinceId=2,Name="سلماس"},
               new City(){ ID=29, ProvinceId=2,Name="شاهین دژ"},
               new City(){ ID=30, ProvinceId=2,Name="ماكو"},
               new City(){ ID=31, ProvinceId=2,Name="مهاباد"},
               new City(){ ID=32, ProvinceId=2,Name="میاندوآب"},
               new City(){ ID=33, ProvinceId=2,Name="نقده"},
               new City(){ ID=34, ProvinceId=3,Name="اردبیل"},
               new City(){ ID=35, ProvinceId=3,Name="بیله سوار"},
               new City(){ ID=36, ProvinceId=3,Name="پارس آباد"},
               new City(){ ID=37, ProvinceId=3,Name="خلخال"},
               new City(){ ID=38, ProvinceId=3,Name="كوثر"},
               new City(){ ID=39, ProvinceId=3,Name="گرمی"},
               new City(){ ID=40, ProvinceId=3,Name="مشگین"},
               new City(){ ID=41, ProvinceId=3,Name="نمین"},
               new City(){ ID=42, ProvinceId=3,Name="نیر"},
               new City(){ ID=43, ProvinceId=4,Name="آران و بیدگل"},
               new City(){ ID=44, ProvinceId=4,Name="اردستان"},
               new City(){ ID=45, ProvinceId=4,Name="اصفهان"},
               new City(){ ID=46, ProvinceId=4,Name="برخوار و میمه"},
               new City(){ ID=47, ProvinceId=4,Name="تیران و كرون"},
               new City(){ ID=48, ProvinceId=4,Name="چادگان"},
               new City(){ ID=49, ProvinceId=4,Name="خمینی شهر"},
               new City(){ ID=50, ProvinceId=4,Name="خوانسار"},
               new City(){ ID=51, ProvinceId=4,Name="سمیرم"},
               new City(){ ID=52, ProvinceId=4,Name="شاهین شهر و میمه"},
               new City(){ ID=53, ProvinceId=4,Name="شهر رضا"},
               new City(){ ID=54, ProvinceId=4,Name="سمیرم سفلی"},
               new City(){ ID=55, ProvinceId=4,Name="فریدن"},
               new City(){ ID=56, ProvinceId=4,Name="فریدون شهر"},
               new City(){ ID=57, ProvinceId=4,Name="فلاورجان"},
               new City(){ ID=58, ProvinceId=4,Name="كاشان"},
               new City(){ ID=59, ProvinceId=4,Name="گلپایگان"},
               new City(){ ID=60, ProvinceId=4,Name="لنجان"},
               new City(){ ID=61, ProvinceId=4,Name="مباركه"},
               new City(){ ID=62, ProvinceId=4,Name="نائین"},
               new City(){ ID=63, ProvinceId=4,Name="نجف آباد"},
               new City(){ ID=64, ProvinceId=4,Name="نطنز"},
               new City(){ ID=65, ProvinceId=5,Name="ساوجبلاق"},
               new City(){ ID=66, ProvinceId=5,Name="كرج"},
               new City(){ ID=67, ProvinceId=5,Name="نظرآباد"},
               new City(){ ID=68, ProvinceId=5,Name="طالقان"},
               new City(){ ID=69, ProvinceId=6,Name="آبدانان"},
               new City(){ ID=70, ProvinceId=6,Name="ایلام"},
               new City(){ ID=71, ProvinceId=6,Name="ایوان"},
               new City(){ ID=72, ProvinceId=6,Name="دره شهر"},
               new City(){ ID=73, ProvinceId=6,Name="دهلران"},
               new City(){ ID=74, ProvinceId=6,Name="شیران و چرداول"},
               new City(){ ID=75, ProvinceId=6,Name="مهران"},
               new City(){ ID=76, ProvinceId=7,Name="بوشهر"},
               new City(){ ID=77, ProvinceId=7,Name="تنگستان"},
               new City(){ ID=78, ProvinceId=7,Name="جم"},
               new City(){ ID=79, ProvinceId=7,Name="دشتستان"},
               new City(){ ID=80, ProvinceId=7,Name="دشتی"},
               new City(){ ID=81, ProvinceId=7,Name="دیر"},
               new City(){ ID=82, ProvinceId=7,Name="دیلم"},
               new City(){ ID=83, ProvinceId=7,Name="كنگان"},
               new City(){ ID=84, ProvinceId=7,Name="گناوه"},
               new City(){ ID=85, ProvinceId=8,Name="اسلام شهر"},
               new City(){ ID=86, ProvinceId=8,Name="پاكدشت"},
               new City(){ ID=87, ProvinceId=8,Name="تهران"},
               new City(){ ID=88, ProvinceId=8,Name="دماوند"},
               new City(){ ID=89, ProvinceId=8,Name="رباط كریم"},
               new City(){ ID=90, ProvinceId=8,Name="ری"},
               new City(){ ID=91, ProvinceId=8,Name="شمیرانات"},
               new City(){ ID=92, ProvinceId=8,Name="شهریار"},
               new City(){ ID=93, ProvinceId=8,Name="فیروزكوه"},
               new City(){ ID=94, ProvinceId=8,Name="ورامین"},
               new City(){ ID=95, ProvinceId=9,Name="اردل"},
               new City(){ ID=96, ProvinceId=9,Name="بروجن"},
               new City(){ ID=97, ProvinceId=9,Name="شهركرد"},
               new City(){ ID=98, ProvinceId=9,Name="فارسان"},
               new City(){ ID=99, ProvinceId=9,Name="كوهرنگ"},
               new City(){ ID=100,ProvinceId=9,Name="لردگان"},
               new City(){ ID=101,ProvinceId=10,Name="بیرجند"},
               new City(){ ID=102,ProvinceId=10,Name="درمیان"},
               new City(){ ID=103,ProvinceId=10,Name="سرایان"},
               new City(){ ID=104,ProvinceId=10,Name="سر بیشه"},
               new City(){ ID=105,ProvinceId=10,Name="فردوس"},
               new City(){ ID=106,ProvinceId=10,Name="قائن"},
               new City(){ ID=107,ProvinceId=10,Name="نهبندان"},
               new City(){ ID=108,ProvinceId=11,Name="برد سكن"},
               new City(){ ID=109,ProvinceId=11,Name="بجستان"},
               new City(){ ID=110,ProvinceId=11,Name="تایباد"},
               new City(){ ID=111,ProvinceId=11,Name="تحت جلگه"},
               new City(){ ID=112,ProvinceId=11,Name="تربت جام"},
               new City(){ ID=113,ProvinceId=11,Name="تربت حیدریه"},
               new City(){ ID=114,ProvinceId=11,Name="چناران"},
               new City(){ ID=115,ProvinceId=11,Name="جغتای"},
               new City(){ ID=116,ProvinceId=11,Name="جوین"},
               new City(){ ID=117,ProvinceId=11,Name="خلیل آباد"},
               new City(){ ID=118,ProvinceId=11,Name="خواف"},
               new City(){ ID=119,ProvinceId=11,Name="درگز"},
               new City(){ ID=120,ProvinceId=11,Name="رشتخوار"},
               new City(){ ID=121,ProvinceId=11,Name="زاوه"},
               new City(){ ID=122,ProvinceId=11,Name="سبزوار"},
               new City(){ ID=123,ProvinceId=11,Name="سرخس"},
               new City(){ ID=124,ProvinceId=11,Name="فریمان"},
               new City(){ ID=125,ProvinceId=11,Name="قوچان"},
               new City(){ ID=126,ProvinceId=11,Name="طرقبه و شاندیز"},
               new City(){ ID=127,ProvinceId=11,Name="كاشمر"},
               new City(){ ID=128,ProvinceId=11,Name="كلات"},
               new City(){ ID=129,ProvinceId=11,Name="گناباد"},
               new City(){ ID=130,ProvinceId=11,Name="مشهد"},
               new City(){ ID=131,ProvinceId=11,Name="مه ولات"},
               new City(){ ID=132,ProvinceId=11,Name="نیشابور"},
               new City(){ ID=133,ProvinceId=12,Name="اسفراین"},
               new City(){ ID=134,ProvinceId=12,Name="بجنورد"},
               new City(){ ID=135,ProvinceId=12,Name="جاجرم"},
               new City(){ ID=136,ProvinceId=12,Name="شیروان"},
               new City(){ ID=137,ProvinceId=12,Name="فاروج"},
               new City(){ ID=138,ProvinceId=12,Name="مانه و سملقان"},
               new City(){ ID=139,ProvinceId=13,Name="آبادان"},
               new City(){ ID=140,ProvinceId=13,Name="امیدیه"},
               new City(){ ID=141,ProvinceId=13,Name="اندیمشك"},
               new City(){ ID=142,ProvinceId=13,Name="اهواز"},
               new City(){ ID=143,ProvinceId=13,Name="ایذه"},
               new City(){ ID=144,ProvinceId=13,Name="باغ ملك"},
               new City(){ ID=145,ProvinceId=13,Name="بندرماهشهر"},
               new City(){ ID=146,ProvinceId=13,Name="بهبهان"},
               new City(){ ID=147,ProvinceId=13,Name="خرمشهر"},
               new City(){ ID=148,ProvinceId=13,Name="دزفول"},
               new City(){ ID=149,ProvinceId=13,Name="دشت آزادگان"},
               new City(){ ID=150,ProvinceId=13,Name="رامشیر"},
               new City(){ ID=151,ProvinceId=13,Name="رامهرمز"},
               new City(){ ID=152,ProvinceId=13,Name="شادگان"},
               new City(){ ID=153,ProvinceId=13,Name="شوش"},
               new City(){ ID=154,ProvinceId=13,Name="شوشتر"},
               new City(){ ID=155,ProvinceId=13,Name="گتوند"},
               new City(){ ID=156,ProvinceId=13,Name="لالی"},
               new City(){ ID=157,ProvinceId=13,Name="مسجد سلیمان"},
               new City(){ ID=158,ProvinceId=13,Name="هندیجان"},
               new City(){ ID=159,ProvinceId=14,Name="ابهر"},
               new City(){ ID=160,ProvinceId=14,Name="ایجرود"},
               new City(){ ID=161,ProvinceId=14,Name="خدابنده"},
               new City(){ ID=162,ProvinceId=14,Name="خرمدره"},
               new City(){ ID=163,ProvinceId=14,Name="زنجان"},
               new City(){ ID=164,ProvinceId=14,Name="طارم"},
               new City(){ ID=165,ProvinceId=14,Name="ماه نشان"},
               new City(){ ID=166,ProvinceId=15,Name="دامغان"},
               new City(){ ID=167,ProvinceId=15,Name="سمنان"},
               new City(){ ID=168,ProvinceId=15,Name="شاهرود"},
               new City(){ ID=169,ProvinceId=15,Name="گرمسار"},
               new City(){ ID=170,ProvinceId=15,Name="مهدی شهر"},
               new City(){ ID=171,ProvinceId=16,Name="ایرانشهر"},
               new City(){ ID=172,ProvinceId=16,Name="چابهار"},
               new City(){ ID=173,ProvinceId=16,Name="خاش"},
               new City(){ ID=174,ProvinceId=16,Name="دلگان"},
               new City(){ ID=175,ProvinceId=16,Name="زابل"},
               new City(){ ID=176,ProvinceId=16,Name="زاهدان"},
               new City(){ ID=177,ProvinceId=16,Name="زهك"},
               new City(){ ID=178,ProvinceId=16,Name="سراوان"},
               new City(){ ID=179,ProvinceId=16,Name="سرباز"},
               new City(){ ID=180,ProvinceId=16,Name="كنارك"},
               new City(){ ID=181,ProvinceId=16,Name="نیكشهر"},
               new City(){ ID=182,ProvinceId=17,Name="آباده"},
               new City(){ ID=183,ProvinceId=17,Name="ارسنجان"},
               new City(){ ID=184,ProvinceId=17,Name="استهبان"},
               new City(){ ID=185,ProvinceId=17,Name="اقلید"},
               new City(){ ID=186,ProvinceId=17,Name="بوانات"},
               new City(){ ID=187,ProvinceId=17,Name="پاسارگاد"},
               new City(){ ID=188,ProvinceId=17,Name="جهرم"},
               new City(){ ID=189,ProvinceId=17,Name="خرم بید"},
               new City(){ ID=190,ProvinceId=17,Name="خنج"},
               new City(){ ID=191,ProvinceId=17,Name="داراب"},
               new City(){ ID=192,ProvinceId=17,Name="زرین دشت"},
               new City(){ ID=193,ProvinceId=17,Name="سپیدان"},
               new City(){ ID=194,ProvinceId=17,Name="شیراز"},
               new City(){ ID=195,ProvinceId=17,Name="فراشبند"},
               new City(){ ID=196,ProvinceId=17,Name="فسا"},
               new City(){ ID=197,ProvinceId=17,Name="فیروزآباد"},
               new City(){ ID=198,ProvinceId=17,Name="قیر و كارزین"},
               new City(){ ID=199,ProvinceId=17,Name="كازرون"},
               new City(){ ID=200,ProvinceId=17,Name="لارستان"},
               new City(){ ID=201,ProvinceId=17,Name="لامرد"},
               new City(){ ID=202,ProvinceId=17,Name="مرودشت"},
               new City(){ ID=203,ProvinceId=17,Name="ممسنی"},
               new City(){ ID=204,ProvinceId=17,Name="مهر"},
               new City(){ ID=205,ProvinceId=17,Name="نی ریز"},
               new City(){ ID=206,ProvinceId=18,Name="آبیك"},
               new City(){ ID=207,ProvinceId=18,Name="البرز"},
               new City(){ ID=208,ProvinceId=18,Name="بوئین زهرا"},
               new City(){ ID=209,ProvinceId=18,Name="تاكستان"},
               new City(){ ID=210,ProvinceId=18,Name="قزوین"},
               new City(){ ID=211,ProvinceId=19,Name="قم"},
               new City(){ ID=212,ProvinceId=20,Name="بانه"},
               new City(){ ID=213,ProvinceId=20,Name="بیجار"},
               new City(){ ID=214,ProvinceId=20,Name="دیواندره"},
               new City(){ ID=215,ProvinceId=20,Name="سروآباد"},
               new City(){ ID=216,ProvinceId=20,Name="سقز"},
               new City(){ ID=217,ProvinceId=20,Name="سنندج"},
               new City(){ ID=218,ProvinceId=20,Name="قروه"},
               new City(){ ID=219,ProvinceId=20,Name="كامیاران"},
               new City(){ ID=220,ProvinceId=20,Name="مریوان"},
               new City(){ ID=221,ProvinceId=21,Name="بافت"},
               new City(){ ID=222,ProvinceId=21,Name="بردسیر"},
               new City(){ ID=223,ProvinceId=21,Name="بم"},
               new City(){ ID=224,ProvinceId=21,Name="جیرفت"},
               new City(){ ID=225,ProvinceId=21,Name="راور"},
               new City(){ ID=226,ProvinceId=21,Name="رفسنجان"},
               new City(){ ID=227,ProvinceId=21,Name="رودبار جنوب"},
               new City(){ ID=228,ProvinceId=21,Name="زرند"},
               new City(){ ID=229,ProvinceId=21,Name="سیرجان"},
               new City(){ ID=230,ProvinceId=21,Name="شهر بابك"},
               new City(){ ID=231,ProvinceId=21,Name="عنبرآباد"},
               new City(){ ID=232,ProvinceId=21,Name="قلعه گنج"},
               new City(){ ID=233,ProvinceId=21,Name="كرمان"},
               new City(){ ID=234,ProvinceId=21,Name="كوهبنان"},
               new City(){ ID=235,ProvinceId=21,Name="كهنوج"},
               new City(){ ID=236,ProvinceId=21,Name="منوجان"},
               new City(){ ID=237,ProvinceId=22,Name="اسلام آباد غرب"},
               new City(){ ID=238,ProvinceId=22,Name="پاوه"},
               new City(){ ID=239,ProvinceId=22,Name="ثلاث باباجانی"},
               new City(){ ID=240,ProvinceId=22,Name="جوانرود"},
               new City(){ ID=241,ProvinceId=22,Name="دالاهو"},
               new City(){ ID=242,ProvinceId=22,Name="روانسر"},
               new City(){ ID=243,ProvinceId=22,Name="سر پل ذهاب"},
               new City(){ ID=244,ProvinceId=22,Name="سنقر"},
               new City(){ ID=245,ProvinceId=22,Name="صحنه"},
               new City(){ ID=246,ProvinceId=22,Name="قصر شیرین"},
               new City(){ ID=247,ProvinceId=22,Name="كرمانشاه"},
               new City(){ ID=248,ProvinceId=22,Name="كنگاور"},
               new City(){ ID=249,ProvinceId=22,Name="گیلان غرب"},
               new City(){ ID=250,ProvinceId=22,Name="هرسین"},
               new City(){ ID=251,ProvinceId=23,Name="بویر احمد"},
               new City(){ ID=252,ProvinceId=23,Name="بهمئی"},
               new City(){ ID=253,ProvinceId=23,Name="دنا"},
               new City(){ ID=254,ProvinceId=23,Name="كهگیلویه"},
               new City(){ ID=255,ProvinceId=23,Name="گچساران"},
               new City(){ ID=256,ProvinceId=24,Name="آزادشهر"},
               new City(){ ID=257,ProvinceId=24,Name="آق قلا"},
               new City(){ ID=258,ProvinceId=24,Name="بندر گز"},
               new City(){ ID=259,ProvinceId=24,Name="بندر تركمن"},
               new City(){ ID=260,ProvinceId=24,Name="رامیان"},
               new City(){ ID=261,ProvinceId=24,Name="علی آباد"},
               new City(){ ID=262,ProvinceId=24,Name="كرد كوی"},
               new City(){ ID=263,ProvinceId=24,Name="كلاله"},
               new City(){ ID=264,ProvinceId=24,Name="گرگان"},
               new City(){ ID=265,ProvinceId=24,Name="گنبد كاووس"},
               new City(){ ID=266,ProvinceId=24,Name="مینو دشت"},
               new City(){ ID=267,ProvinceId=25,Name="آستارا"},
               new City(){ ID=268,ProvinceId=25,Name="آستانه اشرفیه"},
               new City(){ ID=269,ProvinceId=25,Name="املش"},
               new City(){ ID=270,ProvinceId=25,Name="بندر انزلی"},
               new City(){ ID=271,ProvinceId=25,Name="رشت"},
               new City(){ ID=272,ProvinceId=25,Name="رضوانشهر"},
               new City(){ ID=273,ProvinceId=25,Name="رودبار"},
               new City(){ ID=274,ProvinceId=25,Name="رودسر"},
               new City(){ ID=275,ProvinceId=25,Name="سیاهكل"},
               new City(){ ID=276,ProvinceId=25,Name="شفت"},
               new City(){ ID=277,ProvinceId=25,Name="صومعه سرا"},
               new City(){ ID=278,ProvinceId=25,Name="طوالش"},
               new City(){ ID=279,ProvinceId=25,Name="فومن"},
               new City(){ ID=280,ProvinceId=25,Name="لاهیجان"},
               new City(){ ID=281,ProvinceId=25,Name="لنگرود"},
               new City(){ ID=282,ProvinceId=25,Name="ماسال"},
               new City(){ ID=283,ProvinceId=26,Name="ازنا"},
               new City(){ ID=284,ProvinceId=26,Name="الیگودرز"},
               new City(){ ID=285,ProvinceId=26,Name="بروجرد"},
               new City(){ ID=286,ProvinceId=26,Name="پلدختر"},
               new City(){ ID=287,ProvinceId=26,Name="خرم آباد"},
               new City(){ ID=288,ProvinceId=26,Name="دورود"},
               new City(){ ID=289,ProvinceId=17,Name="لامرد"},
               new City(){ ID=290,ProvinceId=17,Name="مرودشت"},
               new City(){ ID=291,ProvinceId=17,Name="ممسنی"},
               new City(){ ID=292,ProvinceId=17,Name="مهر"},
               new City(){ ID=293,ProvinceId=17,Name="نی ریز"},
               new City(){ ID=294,ProvinceId=18,Name="آبیك"},
               new City(){ ID=295,ProvinceId=18,Name="البرز"},
               new City(){ ID=296,ProvinceId=18,Name="بوئین زهرا"},
               new City(){ ID=297,ProvinceId=18,Name="تاكستان"},
               new City(){ ID=298,ProvinceId=18,Name="قزوین"},
               new City(){ ID=299,ProvinceId=19,Name="قم"},
               new City(){ ID=300,ProvinceId=20,Name="بانه"},
               new City(){ ID=301,ProvinceId=20,Name="بیجار"},
               new City(){ ID=302,ProvinceId=20,Name="دیواندره"},
               new City(){ ID=303,ProvinceId=20,Name="سروآباد"},
               new City(){ ID=304,ProvinceId=20,Name="سقز"},
               new City(){ ID=305,ProvinceId=20,Name="سنندج"},
               new City(){ ID=306,ProvinceId=20,Name="قروه"},
               new City(){ ID=307,ProvinceId=20,Name="كامیاران"},
               new City(){ ID=308,ProvinceId=20,Name="مریوان"},
               new City(){ ID=309,ProvinceId=21,Name="بافت"},
               new City(){ ID=310,ProvinceId=21,Name="بردسیر"},
               new City(){ ID=311,ProvinceId=21,Name="بم"},
               new City(){ ID=312,ProvinceId=21,Name="جیرفت"},
               new City(){ ID=313,ProvinceId=21,Name="راور"},
               new City(){ ID=314,ProvinceId=21,Name="رفسنجان"},
               new City(){ ID=315,ProvinceId=21,Name="رودبار جنوب"},
               new City(){ ID=316,ProvinceId=21,Name="زرند"},
               new City(){ ID=317,ProvinceId=21,Name="سیرجان"},
               new City(){ ID=318,ProvinceId=21,Name="شهر بابك"},
               new City(){ ID=319,ProvinceId=21,Name="عنبرآباد"},
               new City(){ ID=320,ProvinceId=21,Name="قلعه گنج"},
               new City(){ ID=321,ProvinceId=21,Name="كرمان"},
               new City(){ ID=322,ProvinceId=21,Name="كوهبنان"},
               new City(){ ID=323,ProvinceId=21,Name="كهنوج"},
               new City(){ ID=324,ProvinceId=21,Name="منوجان"},
               new City(){ ID=325,ProvinceId=22,Name="اسلام آباد غرب"},
               new City(){ ID=326,ProvinceId=22,Name="پاوه"},
               new City(){ ID=327,ProvinceId=22,Name="ثلاث باباجانی"},
               new City(){ ID=328,ProvinceId=22,Name="جوانرود"},
               new City(){ ID=329,ProvinceId=22,Name="دالاهو"},
               new City(){ ID=330,ProvinceId=22,Name="روانس"},
               new City(){ ID=331,ProvinceId=22,Name="سر پل ذهاب"},
               new City(){ ID=332,ProvinceId=22,Name="سنقر"},
               new City(){ ID=333,ProvinceId=22,Name="صحنه"},
               new City(){ ID=334,ProvinceId=22,Name="قصر شیرین"},
               new City(){ ID=335,ProvinceId=22,Name="كرمانشاه"},
               new City(){ ID=336,ProvinceId=22,Name="كنگاور"},
               new City(){ ID=337,ProvinceId=22,Name="گیلان غرب"},
               new City(){ ID=338,ProvinceId=22,Name="هرسین"},
               new City(){ ID=339,ProvinceId=23,Name="بویر احمد"},
               new City(){ ID=340,ProvinceId=23,Name="بهمئی"},
               new City(){ ID=341,ProvinceId=23,Name="دنا"},
               new City(){ ID=342,ProvinceId=23,Name="كهگیلویه"},
               new City(){ ID=343,ProvinceId=23,Name="گچساران"},
               new City(){ ID=344,ProvinceId=24,Name="آزادشهر"},
               new City(){ ID=345,ProvinceId=24,Name="آق قلا"},
               new City(){ ID=346,ProvinceId=24,Name="بندر گز"},
               new City(){ ID=347,ProvinceId=24,Name="بندر تركمن"},
               new City(){ ID=348,ProvinceId=24,Name="رامیان"},
               new City(){ ID=349,ProvinceId=24,Name="علی آباد"},
               new City(){ ID=350,ProvinceId=24,Name="كرد كوی"},
               new City(){ ID=351,ProvinceId=24,Name="كلاله"},
               new City(){ ID=352,ProvinceId=24,Name="گرگان"},
               new City(){ ID=353,ProvinceId=24,Name="گنبد كاووس"},
               new City(){ ID=354,ProvinceId=24,Name="مینو دشت"},
               new City(){ ID=355,ProvinceId=25,Name="آستارا"},
               new City(){ ID=356,ProvinceId=25,Name="آستانه اشرفیه"},
               new City(){ ID=357,ProvinceId=25,Name="املش"},
               new City(){ ID=358,ProvinceId=25,Name="بندر انزلی"},
               new City(){ ID=359,ProvinceId=25,Name="رشت"},
               new City(){ ID=360,ProvinceId=25,Name="رضوانشهر"},
               new City(){ ID=361,ProvinceId=25,Name="رودبار"},
               new City(){ ID=362,ProvinceId=25,Name="رودسر"},
               new City(){ ID=363,ProvinceId=25,Name="سیاهكل"},
               new City(){ ID=364,ProvinceId=25,Name="شفت"},
               new City(){ ID=365,ProvinceId=25,Name="صومعه سرا"},
               new City(){ ID=366,ProvinceId=25,Name="طوالش"},
               new City(){ ID=367,ProvinceId=25,Name="فومن"},
               new City(){ ID=368,ProvinceId=25,Name="لاهیجان"},
               new City(){ ID=369,ProvinceId=25,Name="لنگرود"},
               new City(){ ID=370,ProvinceId=25,Name="ماسال"},
               new City(){ ID=371,ProvinceId=26,Name="ازنا"},
               new City(){ ID=372,ProvinceId=26,Name="الیگودرز"},
               new City(){ ID=373,ProvinceId=26,Name="بروجرد"},
               new City(){ ID=374,ProvinceId=26,Name="پلدختر"},
               new City(){ ID=375,ProvinceId=26,Name="خرم آباد"},
               new City(){ ID=376,ProvinceId=26,Name="دورود"},
               new City(){ ID=377,ProvinceId=26,Name="دلفان"},
               new City(){ ID=378,ProvinceId=26,Name="سلسله"},
               new City(){ ID=379,ProvinceId=26,Name="كوهدشت"},
               new City(){ ID=380,ProvinceId=26,Name="الشتر"},
               new City(){ ID=381,ProvinceId=26,Name="نورآباد"},
               new City(){ ID=382,ProvinceId=27,Name="آمل"},
               new City(){ ID=383,ProvinceId=27,Name="بابل"},
               new City(){ ID=384,ProvinceId=27,Name="بابلسر"},
               new City(){ ID=385,ProvinceId=27,Name="بهشهر"},
               new City(){ ID=386,ProvinceId=27,Name="تنكابن"},
               new City(){ ID=387,ProvinceId=27,Name="جویبار"},
               new City(){ ID=388,ProvinceId=27,Name="چالوس"},
               new City(){ ID=389,ProvinceId=27,Name="رامسر"},
               new City(){ ID=390,ProvinceId=27,Name="ساری"},
               new City(){ ID=391,ProvinceId=27,Name="سوادكوه"},
               new City(){ ID=392,ProvinceId=27,Name="قائم شهر"},
               new City(){ ID=393,ProvinceId=27,Name="گلوگاه"},
               new City(){ ID=394,ProvinceId=27,Name="محمود آباد"},
               new City(){ ID=395,ProvinceId=27,Name="نكا"},
               new City(){ ID=396,ProvinceId=27,Name="نور"},
               new City(){ ID=397,ProvinceId=27,Name="نوشهر"},
               new City(){ ID=398,ProvinceId=27,Name="فریدونكنار"},
               new City(){ ID=399,ProvinceId=28,Name="آشتیان"},
               new City(){ ID=400,ProvinceId=28,Name="اراك"},
               new City(){ ID=401,ProvinceId=28,Name="تفرش"},
               new City(){ ID=402,ProvinceId=28,Name="خمین"},
               new City(){ ID=403,ProvinceId=28,Name="دلیجان"},
               new City(){ ID=404,ProvinceId=28,Name="زرندیه"},
               new City(){ ID=405,ProvinceId=28,Name="ساوه"},
               new City(){ ID=406,ProvinceId=28,Name="شازند"},
               new City(){ ID=407,ProvinceId=28,Name="كمیجان"},
               new City(){ ID=408,ProvinceId=28,Name="محلات"},
               new City(){ ID=409,ProvinceId=29,Name="بندرعباس"},
               new City(){ ID=410,ProvinceId=29,Name="میناب"},
               new City(){ ID=411,ProvinceId=29,Name="بندر لنگه"},
               new City(){ ID=412,ProvinceId=29,Name="رودان-دهبارز"},
               new City(){ ID=413,ProvinceId=29,Name="جاسك"},
               new City(){ ID=414,ProvinceId=29,Name="قشم"},
               new City(){ ID=415,ProvinceId=29,Name="حاجی آباد"},
               new City(){ ID=416,ProvinceId=29,Name="ابوموسی"},
               new City(){ ID=417,ProvinceId=29,Name="بستك"},
               new City(){ ID=418,ProvinceId=29,Name="گاوبندی"},
               new City(){ ID=419,ProvinceId=29,Name="خمیر"},
               new City(){ ID=420,ProvinceId=30,Name="اسدآباد"},
               new City(){ ID=421,ProvinceId=30,Name="بهار"},
               new City(){ ID=422,ProvinceId=30,Name="تویسركان"},
               new City(){ ID=423,ProvinceId=30,Name="رزن"},
               new City(){ ID=424,ProvinceId=30,Name="كبودر آهنگ"},
               new City(){ ID=425,ProvinceId=30,Name="ملایر"},
               new City(){ ID=426,ProvinceId=30,Name="نهاوند"},
               new City(){ ID=427,ProvinceId=30,Name="همدان"},
               new City(){ ID=428,ProvinceId=31,Name="ابركوه"},
               new City(){ ID=429,ProvinceId=31,Name="اردكان"},
               new City(){ ID=430,ProvinceId=31,Name="بافق"},
               new City(){ ID=431,ProvinceId=31,Name="تفت"},
               new City(){ ID=432,ProvinceId=31,Name="خاتم"},
               new City(){ ID=433,ProvinceId=31,Name="صدوق"},
               new City(){ ID=434,ProvinceId=31,Name="طبس"},
               new City(){ ID=435,ProvinceId=31,Name="مهریز"},
               new City(){ ID=436,ProvinceId=31,Name="میبد"},
               new City(){ ID=437,ProvinceId=31,Name="یزد" },
            };
            Builder.Entity<City>().HasData(CitiesList);
            /************************************************************************************************/
        }
    }
}
